name: libya_bakery
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  bordered_text: ^2.0.0
  google_fonts: ^6.1.0
  http: ^1.1.0
  selectable_container: ^1.0.7
  flutter_otp_text_field: ^1.1.1
  otp_pin_field: ^1.2.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  shared_preferences: ^2.2.2
  get: ^4.6.6
  lottie: ^2.6.0
  geolocator: ^10.1.0
  path: ^1.8.3
  file_picker: ^6.1.1
  drop_down_list: ^0.0.6
  image_picker: ^1.0.5
  google_maps_flutter: ^2.5.0
  get_storage: ^2.1.1
  jiffy: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: ArabicUIDisplay
      fonts:
        - asset: assets/fonts/ArabicUIDisplay.otf
        - asset: assets/fonts/ArabicUIDisplayBlack.otf
          style: italic
    - family: ArabicUIDisplayBold
      fonts:
        - asset: assets/fonts/ArabicUIDisplayMedium.otf
        - asset: assets/fonts/ArabicUIDisplayBold.otf
          weight: 600

uses-material-design: true
